apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
data:
  TYPEORM_CONNECTION: "{{ .Values.DB_DRIVE }}"
  TYPEORM_HOST: "{{ .Values.DB_HOST }}"
  TYPEORM_USERNAME: "{{ .Values.DB_USER }}"
  TYPEORM_PASSWORD: "{{ .Values.DB_PASSWORD }}"
  TYPEORM_DATABASE: "{{ .Values.DB_DATABASE }}"
  TYPEORM_PORT: "{{ .Values.DB_PORT }}"
  TYPEORM_SYNCHRONIZE: "{{ .Values.DB_SYNC }}"
  TYPEORM_LOGGING: "{{ .Values.DB_LOG }}"
  TYPEORM_ENTITIES: "entity/*.js,dist/**/entity/**/*.js"
