apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.appName }}
  template:
    metadata:
      name: {{ .Values.appName }}
      labels:
        name: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.DOCKER_REGISTRY }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ .Values.appName }}
      restartPolicy: Always
