apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    name: {{ .Values.appName }}
spec:
  selector:
    name: {{ .Values.appName }}
  ports:
    - port: 3000
      name: api
      appProtocol: TCP
      targetPort: 3000
  type: ClusterIP
